from pathlib import Path


class IrisConstants:
    """Centralised constants for the Iris data pipeline.

    Attributes:
        KAGGLE_API_BASE (str): Base URL for the Kaggle public REST API.
        IRIS_OWNER (str): Kaggle dataset owner slug.
        IRIS_DATASET (str): Kaggle dataset name slug.
        IRIS_FILENAME (str): Target CSV filename inside the downloaded archive.
        DOWNLOAD_TIMEOUT_S (int): HTTP request timeout in seconds for dataset
            downloads.
        CHUNK_SIZE (int): Read chunk size in bytes used when streaming the
            downloaded zip file.
        PUBLIC_DIR (Path): Container-side path to the shared volume root
            (bind-mounted from ``./public`` on the host).
        FEATURE_STORAGE_DIR (Path): Subdirectory for the transformed feature
            store CSV (``public/feature_storage/``).
        FEATURE_STORE_FILENAME (str): Filename for the feature store CSV.
        SOURCE_DATA_DIR (Path): Subdirectory for externally generated source
            data (``public/source_data/``).
        SIMULATED_CSV_FILENAME (str): Filename for the synthetic / simulated
            Iris CSV generated by the ``generate_synthetic_data`` DAG.
        PREDICTION_STORAGE_DIR (Path): Subdirectory where the inference API
            appends every prediction (``public/prediction_storage/``).
        PREDICTIONS_FILENAME (str): Filename for the rolling prediction log
            written by the API on every ``POST /predict`` call.
    """

    # -- Kaggle API -----------------------------------------------------------
    KAGGLE_API_BASE: str = "https://www.kaggle.com/api/v1"
    IRIS_OWNER: str = "uciml"
    IRIS_DATASET: str = "iris"
    IRIS_FILENAME: str = "Iris.csv"

    # -- Download settings ----------------------------------------------------
    DOWNLOAD_TIMEOUT_S: int = 120
    CHUNK_SIZE: int = 8 * 1024  # 8 KB

    # -- Shared volume root ---------------------------------------------------
    PUBLIC_DIR: Path = Path("/public")

    # -- Feature storage (transformed training data) --------------------------
    FEATURE_STORAGE_DIR: Path = PUBLIC_DIR / "feature_storage"
    FEATURE_STORE_FILENAME: str = "features_iris.csv"

    # -- Source data (simulated / synthetic batches) --------------------------
    SOURCE_DATA_DIR: Path = PUBLIC_DIR / "source_data"
    SIMULATED_CSV_FILENAME: str = "simulated.csv"

    # -- Prediction storage (written by the inference API) --------------------
    PREDICTION_STORAGE_DIR: Path = PUBLIC_DIR / "prediction_storage"
    PREDICTIONS_FILENAME: str = "predicted.csv"

    def __new__(cls) -> "IrisConstants":
        """Prevent instantiation; use class attributes directly."""
        raise TypeError(f"{cls.__name__} is not meant to be instantiated.")


class MLFlowConstants:
    """Centralised constants for the MLFlow integration.

    This class is not meant to be instantiated; use its attributes directly
    as class-level references (e.g. ``MLFlowConstants.EXPERIMENT_NAME``).

    Attributes:
        EXPERIMENT_NAME (str): MLFlow experiment name for Iris classification
            training runs.
        TRACKING_URI_ENV (str): Name of the environment variable that holds
            the MLFlow tracking server URI.
        DEFAULT_TRACKING_URI (str): Fallback tracking URI used when the
            ``MLFLOW_TRACKING_URI`` environment variable is not set.
        ARTIFACT_DIR (str): Container-side path to the MLFlow artifact store
            (bind-mounted from ``./mlflow/artifacts`` on the host).
        REGISTERED_MODEL_NAME (str): Single registered model name used across
            all classifier families. Only the overall best-performing model
            from each DAG run is registered here; a new version is only
            created when it outperforms the current ``champion``.
        CHAMPION_ALIAS (str): Alias assigned to the latest best-performing
            registered model version, enabling deployment tooling to always
            resolve the production-ready model without hard-coding a version
            number.
    """

    EXPERIMENT_NAME: str = "iris_classification"
    TRACKING_URI_ENV: str = "MLFLOW_TRACKING_URI"
    DEFAULT_TRACKING_URI: str = "http://mlflow:5000"
    ARTIFACT_DIR: str = "/mlflow/artifacts"
    REGISTERED_MODEL_NAME: str = "iris_classifier"
    CHAMPION_ALIAS: str = "champion"

    def __new__(cls) -> "MLFlowConstants":
        """Prevent instantiation; use class attributes directly."""
        raise TypeError(f"{cls.__name__} is not meant to be instantiated.")


class DriftConstants:
    """Constants for data-drift detection.

    Attributes:
        KS_ALPHA (float): Significance level for the two-sample
            Kolmogorov-Smirnov test.  A feature is flagged as drifted when
            its p-value falls below this threshold.
        TRAINING_DAG_ID (str): DAG ID of the standalone training pipeline
            triggered automatically when drift is detected.
    """

    KS_ALPHA: float = 0.05
    TRAINING_DAG_ID: str = "training_pipeline"

    def __new__(cls) -> "DriftConstants":
        """Prevent instantiation; use class attributes directly."""
        raise TypeError(f"{cls.__name__} is not meant to be instantiated.")
